### ISSUE TITLE
Add a reference to Github on the Curseforge page

### ISSUE THREAD

**Issue by bibo38** [AllenSeitz/DimDungeons#1]
Hi,

i\ve tried to get your source code, but couldn't find a reference to it on the Curseforge page. And since the Repository wasn't named Dimensional Dungeons, my quick search on GitHub resulted into no results.

But by pure luck, I've found the following book in a dungeon:
![GitHub reference in a dungeon book](https://user-images.githubusercontent.com/1812304/71367257-cf3d8080-25a4-11ea-89ac-2658f2b11778.png)

After some more searching I've finally found the repository (knowing it must be on GitHub :smirk: ).

It would be nice, if you could add the repository as a link to the Curseforge page (You can add a "Source" entry to the top menu, which can be a link to the GitHub repository). And if you don't want to manage two issue trackers, you can also dismiss the Curseforge issue tracker and add a link to the GitHub issue tracker.

See https://www.curseforge.com/minecraft/mc-mods/baubles for an example of an link to the source code and the GitHub issue tracker.

**Comment by AllenSeitz** [comment]
Oh thank you. I missed that. It is done now.
