### ISSUE TITLE
Mahou Tsukai Explosion bug

### ISSUE THREAD

**Issue by BSG-Ori** [AllenSeitz/DimDungeons#10]
Pack: All The Mods 5
Version 2.2

Mods in question:
DimDungeions Version: dimdungeons-1.06-forge-1.15.2.jar
Mahou Tsukai: mahoutsukai-1.15.2-v1.18.2.jar

The item in question is the Staff of Explosive Mana Condensation. Allows players to break the blocks of the dungeon and escape into the outer area and explode other Dungeons. I assume this is unintended, and I will be reporting it to Mahou Tsukai as well.

**Comment by AllenSeitz** [comment]
Thank you! Yeah I tried to ban all explodey things, such as creepers, But there's nothing I can do about other mods adding them back in.

Maybe in 1.16 there might be a way for me to cancel explosions dimension-wide, but then again some of my room designs involve explosions and obsidian.

**Comment by AllenSeitz** [comment]
For what it's worth, in 1.16 there WAS a way for me to cancel or modify unwanted explosions after all. Yay!
