### ISSUE TITLE
Add a separate creative tab for the Mod items

### ISSUE THREAD

**Issue by bibo38** [AllenSeitz/DimDungeons#2]
While testing the mod in the creative mode, i've noticed, that it didn't have a separate tab in the creative inventory. I would personally prefer to have all of the mods items in a mod specific inventory tab to easily find my desired items.

**Comment by AllenSeitz** [comment]
Good idea. I'll make this part of the 1.15 port. Right now I have a content update for 1.14.4 that is nearly done.
