### ISSUE TITLE
[1.16.5] Casting ClientWorld to ServerWorld

### ISSUE THREAD

**Issue by UnseenAcademical** [AllenSeitz/DimDungeons#20]
Managed to successfully put the blocks together in Creative, got into a dungeon. Found a dispenser with an oak button next to it in a room full of beds. Right clicked the button. Crashed with this error:

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
Exit Code: -1

Successfully able to replicate it upon reloading the world.

**Comment by AllenSeitz** [comment]
I can't replicate this. Are you playing single player or on a server?

There's also nothing modded here. It's just a vanilla dispenser, containing 3 ordinary lingering potions of Healing II, with an oak button. If you build that setup in the Overworld does that crash too?

**Comment by UnseenAcademical** [comment]
Single player, but it crashes outside the dimension when making the same contraption. I'll keep testing to see what might be making redstone unhappy.
