### ISSUE TITLE
Gravestone Mod problems

### ISSUE THREAD

**Issue by vendair** [AllenSeitz/DimDungeons#21]
If the gravestone mod is being used and a player does in the dungeon , the gravestone will remain (possibly blocking paths) and will be unmineable leaving both the loot unretrievable and again the possibility of blocking paths.

**Comment by AllenSeitz** [comment]
This was my main motivation for implementing the block breaking whitelist. If you look in the server config (.minecraft/saves/[your world name]/serverconfig/dimdungeons-server.toml) there will be an empty array that you acn add "gravestones:gravestone" to. I think that should fix it.

**Comment by AllenSeitz** [comment]
Actually, please let me know what the block id is if I didn't guess it correctly just now. I'll add it ot the default config in the next version when I close this ticket.

**Comment by vendair** [comment]
Unfortunately it’s not my server but happy to provide help, the block ID is gravestone:gravestone. Thank you for help I’ll keep that stored in case I host in the future

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AllenSeitz** [comment]
1.093 adds gravestone:gravestone to the default block breaking whitelist. Version 1.1 will force a config regeneration. Thank you for your help!
