### ISSUE TITLE
Portal Crown block can lose it's texture

### ISSUE THREAD

**Issue by Winddbourne** [AllenSeitz/DimDungeons#24]
![2021-03-24_20 47 12](https://user-images.githubusercontent.com/24589533/112402393-d771f780-8ce2-11eb-9905-05c3e95d3e7f.png)

As you can see in the picture I tried to place a stone block on top of the portal crown block in creative and got the error texture.  I repeated this using dirt as well, and then glass confirming that it also happens with transparent blocks. 

It does not happen with another crown block. That gives you a rather nice pillar . . . but if you try to use them as a normal fence they don't hook together, or attach to other wall blocks.  

Here are some more images:

![2021-03-24_20 56 27](https://user-images.githubusercontent.com/24589533/112402816-975f4480-8ce3-11eb-9f13-5981ae210b1b.png)

![2021-03-24_20 56 39](https://user-images.githubusercontent.com/24589533/112402827-9dedbc00-8ce3-11eb-9741-53f1c2fe8a0a.png)

![2021-03-24_20 56 56](https://user-images.githubusercontent.com/24589533/112402839-a6de8d80-8ce3-11eb-8a96-58e7d011b11f.png)

![2021-03-24_20 56 58](https://user-images.githubusercontent.com/24589533/112402858-ad6d0500-8ce3-11eb-86b0-daae7e46081c.png)

I don't think this is what you had in mind. lol

**Comment by AllenSeitz** [comment]
Good find. I need to look at my wall models some more.

**Comment by AllenSeitz** [comment]
Unable to load model: 'dimdungeons:block/template_wall_side_tall' referenced from: dimdungeons:block_portal_crown#east=none,north=none,south=none,up=true,waterlogged=true,west=none: java.io.FileNotFoundException: dimdungeons:models/block/template_wall_side_tall.json

oh that's bad
