### ISSUE TITLE
Questions Regarding Themed Dungeons

### ISSUE THREAD

**Issue by NJL5390** [AllenSeitz/DimDungeons#32]
Hi,

I've recently been putting together my own themed dungeons using a custom datapack for a custom modpack I'm making and I was wondering if there's a way to specify the "name" of a themed dungeon? What I mean by this is how the nether fortress theme included with this mod has it's proper name. Whereas my custom one is just called "theme 2".

![2021-08-10_13 58 13](https://user-images.githubusercontent.com/64381954/128872261-0ffe045e-6601-4791-8fec-77cd15e1e18a.png)
So what I would like is that instead of the key being "The Theme 2 of Humor" it would be "The Ice Palace of Humor" or a name that I specify instead of just "Theme 2" , "Theme 3" etc. Is there a way to do this? 

Also would it be possible to give themed dungeons large rooms, similar to what the advanced dungeons have? This would allow me to do a lot more with these dungeons!

Thanks for the great mod and keep up the good work!

**Comment by AllenSeitz** [comment]
If you look in the en_us.json file for my mod that will explain everything.
    "npart.dimdungeons.theme_1": "Nether Fortress",
    "npart.dimdungeons.theme_2": "Theme 2",
    "npart.dimdungeons.theme_3": "Theme 3",
    "npart.dimdungeons.theme_4": "Theme 4",
    
I guess that also means that theme 5 is probably showing up for you as "Key to the npart.dimdungeons.theme_5 of Wonder"

As for the big rooms, someday. The problem is making themes that do use them, and themes that don't use them, compatible.  Big room generation is already kind of hardcoded, and it wouldn't play well with small dungeon sizes. And he config is already complicated enough as it is. And so is the code that procedurally builds the dungeons. I want to do it but this mod already a big programming project. (And a hobby.) Thank you for the encouragement though! That's the best way to help ensure it gets done eventually.

**Comment by NJL5390** [comment]
> If you look in the en_us.json file for my mod that will explain everything.
> "npart.dimdungeons.theme_1": "Nether Fortress",
> "npart.dimdungeons.theme_2": "Theme 2",
> "npart.dimdungeons.theme_3": "Theme 3",
> "npart.dimdungeons.theme_4": "Theme 4",
> 
> I guess that also means that theme 5 is probably showing up for you as "Key to the npart.dimdungeons.theme_5 of Wonder"

So, I can change what they say using a resource pack is what you're saying?

> As for the big rooms, someday. The problem is making themes that do use them, and themes that don't use them, compatible. Big room generation is already kind of hardcoded, and it wouldn't play well with small dungeon sizes. And he config is already complicated enough as it is. And so is the code that procedurally builds the dungeons. I want to do it but this mod already a big programming project. (And a hobby.) Thank you for the encouragement though! That's the best way to help ensure it gets done eventually.

I see, That sounds like a lot of work went into this mod! I'm thankful for it as it's a great mod and very fun to use and play around with! Take your time with the big rooms. I have plenty I can play around with in the meantime!

**Comment by NJL5390** [comment]
> So, I can change what they say using a resource pack is what you're saying?

Nevermind, I figured it out and was able to create a resource pack! Thanks for your help and for the fantastic mod! I've had an absolute blast using it and can't wait to make more rooms and dungeons with it!
![2021-08-11_22 34 19](https://user-images.githubusercontent.com/64381954/129106777-20911db2-94f7-4c58-a881-0da730d72266.png)

**Comment by AllenSeitz** [comment]
I'm glad you figured it out and that building for Dim Dungeons is something that you enjoy. When your project is finished feel free to advertise it on the CurseForge page and/or my Discord. I like seeing what people are doing with my mod.
