### ISSUE TITLE
Portal not Spawning

### ISSUE THREAD

**Issue by Alpha-Flyte** [AllenSeitz/DimDungeons#34]
I created the portal exactly how the book mentioned and inserted a key in and ... nothing. No portal appears, though the texture of the keyhole does appear to be correct.

Minecraft ver 1.18.1
Forge ver. 39.0.19

Have not tested standalone, done in creative with other mods such as Quark, Create, Artifacts, Gravestones, Aquaculture, etc.

Edit: For some reason, when I try to take a screenshot of the portal, it shows up here as a mojang loading screen. very strange. seems i cant supply a proper screencap, but please trust me that i did inscribe a key then inserted it into a step by step frame

**Comment by Alpha-Flyte** [comment]
![image](https://user-images.githubusercontent.com/75723066/149345083-7ed1c861-aa77-4b96-ae15-5812023f386c.png)
![image](https://user-images.githubusercontent.com/75723066/149345124-4bac5775-6996-4330-b86f-88f74369cbcd.png)

**Comment by Alpha-Flyte** [comment]
![image](https://user-images.githubusercontent.com/75723066/149345245-c641cce5-872e-4c07-81b5-1ae6ea2b05e5.png)

**Comment by Alpha-Flyte** [comment]
Never mind, it appears that after reloading Minecraft and playing today, the portal opens after a brief while.

**Comment by AllenSeitz** [comment]
Yeah sorry about that. For anyone else searching issues and reading this, in 1.18.1 there is a significant lag spike as the 8x8 chunk dungeon is generated. For me it lasts about 3 seconds. Some players more, some less.
