### ISSUE TITLE
Game crashes when leaving the dungeon dimension as of latest forge version

### ISSUE THREAD

**Issue by NJL5390** [AllenSeitz/DimDungeons#36]
Forge Version: 39.0.55
Minecraft Version: 1.18.1
Dimensional Dungeons Version: 1.13.2
Crash Report: https://gist.github.com/NJL5390/c87eac856907b5c191262d815cb879be

After testing out the new 1.18.1 version of the mod, I found that when I updated to the latest forge version, I got this crash whenever I left the dungeon dimension through an exit portal. 

The crash detailed in the crash report is the same crash I've had with a couple of other mods when updating to this latest forge version, so I would assume that this crash, like the other ones I've had are related to recent changes to forge, especially since this only started happening after I updated Forge.

Just letting you know that this seems to be an issue with your mod as well. 

Thanks again for updating this mod!

**Comment by AllenSeitz** [comment]
Thank you for the report! You nailed it on all accounts. I uploaded 1.13.3 last night and tested it in SMP. The fix worked for me where 1.13.2 broke.

**Comment by NJL5390** [comment]
I can confirm that this update fixed this issue for me as well! Thanks a lot for your help! I look forward to seeing what new things you have in store for this mod!
