### ISSUE TITLE
Mod Compat Corail Tombstone

### ISSUE THREAD

**Issue by slard3** [AllenSeitz/DimDungeons#4]
I died in a Dimensional Dungeon and I can't interact with my tombstone.
The mod ["Corail Tombstone"](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone) adds a tombstone block in the spot you died, and keys to open them to recover your items.

**Comment by AllenSeitz** [comment]
This should be fixed in the newly released 1.05 version.
