### ISSUE TITLE
key not working on the endportalblock, still a blank portal key

### ISSUE THREAD

**Issue by KonekoYumi** [AllenSeitz/DimDungeons#41]
Hi! We downloaded dimensional dungeons  for 1.18.1.
When we try to activate the blank portal key nothing happens - do you know what the problem could be?
Thank you!

**Comment by AllenSeitz** [comment]
Thank you for reporting the issue. A handful of people have reported the issue as well, and unfortunately I don't know what causes it yet. At this point I've ruled out mod conflicts (though not completely), Forge 39.0.8 or .64, and Forge 39.1.0.

If you can please, type "/forge dimensions" and make a note of what it says. This should print a list of every dimension in your world. If dimdungeons:dungeon_dimension is not listed then something happened during initialization to either prevent my mod's datapack from loading, or to prevent my event handlers from being registered. I'm out of ideas but if you can think of anything or if you see anything in a logfile please let me know. Thank you.

**Comment by AllenSeitz** [comment]
The error would be on the server and would appear exclusively in the server's log. Because I assume you only see the problem in a dedicated server environment, right? That's been the pattern so far.

**Comment by AllenSeitz** [comment]
Was this issue fixed by 1.14 for Forge 1.18.1?

And if no, was it fixed by 1.14 for Forge 1.18.2? I'm still not exactly sure what the problem ever was but word of mouth is that some players are reporting that it works again.

**Comment by AllenSeitz** [comment]
I may finally have found the issue and a potential fix. Go into the server config and change this setting:

worldborderToRespect = "minecraft:overworld"

If it was set to dimdungeons:dungeon_dimension then change it to minecraft:overworld. Does that solve your problem? If it does I would love to hear it.

**Comment by sackboy338** [comment]
I tried your fix on my server, and I am still unable to inscribe portal keys. I am on version 1.14 for 1.18.1. Any help would be appreciated.

**Comment by AllenSeitz** [comment]
Thank you. I'll keep looking into it.

**Comment by AllenSeitz** [comment]
I received a new report about this issue.

Does the issue only occur on End Portal Frames which used to contain an eye? (That you previously removed with a key, and made empty again?) If so, holding the right mouse button down for longer might solve the issue.

As well, using an End Portal Frame that never contained an eye or using the alternate Key Inscribing Station should also be glitch free. The issue seems to be something with the "crowbar" function not working or not synchronizing correctly.
