### ISSUE TITLE
compat with mining gadgets

### ISSUE THREAD

**Issue by zzyzzyzzx** [AllenSeitz/DimDungeons#5]
in your dungeons you can not break blocks, this is bypassed by mining gadgets though, not sure if its on your end or their end

**Comment by AllenSeitz** [comment]
Thank you for the report! In the case of Building Gadgets it was a bug on their end. So I suspect the same will be true of Mining Gadgets too. My custom dimension overrides canMineBlock() and causes it to return false most of the time. Other mods should check for this and respect it.

To be fair, I think Dimensional Dungeons is the first and only 1.14 mod to override this function. This function exists in vanilla but it is literally just { return true; }. So no mod author would be expecting that.
