### ISSUE TITLE
Dimension not loading. At all.

### ISSUE THREAD

**Issue by MagmaBro123** [AllenSeitz/DimDungeons#6]
Entering the dimension, nothing loads. I have to force quit to leave the game. Mod is basically useless atm.

No crashes/logs. Tested latest version of Forge and this mod on 1.15.2.

**Comment by AllenSeitz** [comment]
I'm sorry for not responding on github for a month. I should have responded to this ticket as quickly as I do in other places.

It sounds like the game is hung while generating the chunks? If that is the case can you tell me which version of Forge and which version of this mod you are using? And also if you are using any other mods.
