### ISSUE TITLE
"Blank Portal Key" cannot be activated in Magma core servers.

### ISSUE THREAD

**Issue by FirDragon** [AllenSeitz/DimDungeons#60]
"Blank Portal Key" cannot be activated through [Ender Gateway] in [Magma] core server. Because in the [Magma] core "useOn" returns anything other than "InteractionResult.SUCCESS" or "InteractionResult.CONSUME" will lose modifications to item "nbt".
About:
https://github.com/AllenSeitz/DimDungeons/blob/a3f6e3a6fe931544698bba335b4bf24b97160fed/src/main/java/com/catastrophe573/dimdungeons/item/ItemPortalKey.java#L506

**Comment by AllenSeitz** [comment]
I think I understand what you are saying, In the next 1.18.2 build I will return Interaction.SUCCESS when a key is activated and PASS only when using the key does not do anything.

**Comment by AllenSeitz** [comment]
Fixed in the latest release! Download v172 and let me know if the issue still isn't fixed.
