### ISSUE TITLE
Items can be placed in item frames but can't be taken out.

### ISSUE THREAD

**Issue by StormCountTwo** [AllenSeitz/DimDungeons#65]
This happened in the slot machine room, where I was right-clicking the button, missed the button and right-click the item frame behind it. My sword got into the item frame and because block breaking is disabled I couldn't get it out. Perhaps making sure all item frames in the dungeon have something in it could help eliminate this problem. Thanks!

**Comment by AllenSeitz** [comment]
Thank you for the feedback. I will fix that bug in the next version. (For 1.19 and 1.20.)

In the meantime any op (or yourself in single player) can use /data merge entity [look at it and press tab] {Invulnerable:0} to make the item frame breakable so your sword pops out.
