### ISSUE TITLE
"structure block: generate nether star blocks" error

### ISSUE THREAD

**Issue by katubug** [AllenSeitz/DimDungeons#66]
I'll be honest, I don't know enough about how this works to properly report it, but this happened on our server today:

![2023-07-04_11 00 48](https://github.com/AllenSeitz/DimDungeons/assets/20935286/15c74738-96e3-4d97-a386-2f921ab506b9)
(chat is relevant)

We're using 1.2.0 of the Cottage Witch: Recast modpack

**Comment by AllenSeitz** [comment]
Your report is good enough, thank you.

There was a serious flaw in my implementation of the "LockWithCode" idea in version 177, where it was introduced. A few days ago I uploaded a newer version that removes this data block entirely. (That particular chest will just be unlocked, like it was before 177.)

Thank you for playing Dimensional Dungeons! Please let the creator of your modpack know that there is an important update to my mod.

**Comment by katubug** [comment]
Thanks for the update! We'll get the mod updated asap
