### ISSUE TITLE
Rare (Green) Keys.

### ISSUE THREAD

**Issue by chaseyrt** [AllenSeitz/DimDungeons#7]
It seems that they don't work in the overworld, or is there something I'm missing?

**Comment by AllenSeitz** [comment]
This isn't explained very well in the game. But in the room where you found that key, the example portal that you took the key out of contains functional modifications. Modify your portal to match that one.

https://github.com/AllenSeitz/DimDungeons/wiki/Advice-About-Advanced-Dungeons

**Comment by chaseyrt** [comment]
Oh, That's what those weird "fence" looking blocks are! Ok, thanks!
