### ISSUE TITLE
[sugestion] Clientside config option to disable the fullbright effect in the dungeons dimension

### ISSUE THREAD

**Issue by MizzyMizi** [AllenSeitz/DimDungeons#75]
I think it's a bit annoying

**Comment by AllenSeitz** [comment]
I don't want the dungeons to have maximum ambient light. Many of the rooms were designed to have dark corners and light sources were placed thoughtfully. But about a year or two ago I noticed a bug where certain chunks (and whole rooms) would not get a lighting update after being built if there was no ambient light in the dimension. This created glitchy looking blacked out rooms. The only reliable fix I could find was to turn on ambient dimension lighting.

I'll try restoring natural lighting in the next update. In the meantime if you want to play the dungeons as they're intended to be played then you can try using a datapack to change the ambient_light parameter of the dungeon_dimension dimension type from 0.5 back to 0.0.

(Refer to this page of the Dimensional Dungeons wiki if you're unfamiliar with data packs: https://github.com/AllenSeitz/DimDungeons/wiki/Datapacks-for-Dummies.)

If you do try turning the ambient lights off please let me know how that works for you, and which version of Minecraft you're on.

**Comment by MizzyMizi** [comment]
Mostly works for 1.20.1, there were rarely some small odd spots but nothing else.

**Comment by AllenSeitz** [comment]
Thank you!
