### ISSUE TITLE
Does it possible port to 1.12?

### ISSUE THREAD

**Issue by sergeycherepanov** [AllenSeitz/DimDungeons#9]
Hi, I am interesting to try port it to 1.12 because a lot of mods still support the 1.12 only. 

How much effort do you think it takes? Or may be it impossible by some reasons.

**Comment by AllenSeitz** [comment]
Unfortunately 1.12 would be too hard. This mod depends on the Forge API for implementing new blocks and dimensions and Forge has entirely changed between 1.12 and 1.14. There isn't much Java code in this mod but I think nearly every line of code would have to be rewritten for 1.12.

Furthermore the content doesn't back port very well either. My room structures use a lot of the new blocks added in 1.13 and 1.14 and those rooms would break or need cosmetic modifications. I also designed many rooms to use new mechanics such as waterlogging, crawling, and changes to dispensers and redstone comparitors. And item frames on the floor. More than I can remember. So the content would need to be revised too.

I actually started developing this mod on 1.12 and I had a dysfunctional beta. It wasn't until I upgraded to Forge 1.13 (which never had a stable version) that Dimensional Dungeons finally worked. I can't imagine going back.
